### PR TITLE
implement timings struct

### PR DESCRIPTION
**Pull request by fabiosantoscode**
I didn't concern myself with performance at all, because the timings functions will only be called a few times.

### CODE REVIEW

**Comment by kdy1** [comment]
Thanks!
I think it can be changed to an option in the future, but it's not important at the moment.

**Comment by fabiosantoscode** [comment]
Btw I couldn't test this. I'm struggling to use the minifier API. Though I've reviewed it carefully.

**Comment by kdy1** [comment]
What do you mean by
> I'm struggling to use the minifier API

Do you mean using the minifier from node side?

**Comment by fabiosantoscode** [comment]
No, from the rust side. I'm trying to create a Module but it's not going well :)

**Comment by fabiosantoscode** [comment]
Granted I didn't try too much and I'm new at rust, but I faced a number of problems, for example not having the scoped-tls set or what to put there.

**Comment by kdy1** [comment]
I see. Although the value required for each tls differs, https://github.com/swc-project/swc/blob/master/src/lib.rs#L425-L434 and https://github.com/swc-project/swc/blob/9381d0dbc2b0fc80b53c2654126b2d9937253a71/src/lib.rs#L65-L73 would be a good guideline for them.


`swc_common::GLOBALS` is used to manage identifiers or to identify nodes.
Note that it's stored as a thread-local storage, but actually it's shared between threads.

For the first usage, you can see a document at https://rustdoc.swc.rs/swc_ecma_transforms_base/resolver/fn.resolver_with_mark.html
For the second usage, as `Mark::fresh` creates a globally unique mark (with respect to the instance of `swc_common::Globals`) it can be used to make each span unique.


`swc_ecma_utils::HANDLER` is used to report errors from transform passes. Currently, It's not used by any transform, but it may in the future.


`swc_ecma_transforms_base:: helpers::HELPERS` is used to manage helper scripts like `_inherits` from babel.
The instance contains flags where each flag denotes if a helper script should be injected.



Hope it helps and please ask me if you think anything is ambiguous.
I'm going to add documents to those thread-local variables, but I'm not sure if the explanation is clear.

**Pull request merged**
